//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giris_Sayfasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Email { get; set; }
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public Nullable<bool> GecerliFlg { get; set; }
        public string OlusturanAdi { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public string GuncelleyenAdi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public string Rol { get; set; }
    
        public virtual tblKullaniciRol tblKullaniciRol { get; set; }
    }
}
