//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giris_Sayfasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullaniciRol
    {
        public int KullaniciRolID { get; set; }
        public Nullable<int> RolID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public bool GecerliFlg { get; set; }
    
        public virtual tblRol tblRol { get; set; }
        public virtual tblKullanici tblKullanici { get; set; }
    }
}
