//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giris_Sayfasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMail
    {
        public int ID { get; set; }
        public string Alici { get; set; }
        public Nullable<bool> GecerliFlg { get; set; }
        public string Konu { get; set; }
        public string Govde { get; set; }
        public Nullable<byte> DurumFlg { get; set; }
        public Nullable<System.DateTime> GondermeTarihi { get; set; }
        public string HataMesaji { get; set; }
        public Nullable<System.DateTime> Credate { get; set; }
        public string Creuser { get; set; }
    }
}
